---

- name: "Play to test conditional logic"
  hosts: all
  gather_facts: true
  connection: network_cli

  tasks:
    - name: Task1
      debug:
        msg: "Interface {{ item ['key'] }} has an IP address of {{ item['value']['ipv4']['0']['address'] }}"
      loop: "{{ ansible_net_interfaces | dict2items }}"
      when: item['value']['lineprotocol'] == "up"