--- 

- name: "IP Filter test"
  hosts: "10.0.0.101"

  tasks:
    - name: "IP addr filter stuff"
      vars:
        myip: 
          - "192.168.555.1"
          - "192.168.55.1"
          - "8.8.8.8"
          - "10.0.0.1"
          - "2001:db8:aaaa:bbbb::2"
      debug:
        msg: "{{ myip | ansible.utils.ipaddr }}"